# Generated by Django 3.2 on 2022-02-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_start', models.TimeField()),
                ('lunch_end', models.TimeField()),
                ('dinner_start', models.TimeField()),
                ('dinner_end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_opening', models.TimeField()),
                ('weekday_closing', models.TimeField()),
                ('weekend_opening', models.TimeField()),
                ('weekend_closing', models.TimeField()),
            ],
        ),
    ]
