# Generated by Django 3.2 on 2022-02-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodTimes',
            new_name='FoodTime',
        ),
        migrations.RenameModel(
            old_name='OpeningTimes',
            new_name='OpeningTime',
        ),
    ]
