# Generated by Django 3.2 on 2022-02-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': ' Events'},
        ),
        migrations.AlterModelOptions(
            name='foodtime',
            options={'verbose_name_plural': ' Food Times'},
        ),
        migrations.AlterModelOptions(
            name='openingtime',
            options={'verbose_name_plural': ' Opening Times'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_info',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
