# Generated by Django 3.2 on 2022-02-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='FoodTime',
        ),
        migrations.DeleteModel(
            name='OpeningTime',
        ),
    ]
