# Generated by Django 3.2 on 2022-02-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220225_0226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningTime',
            new_name='Opening',
        ),
    ]
