# Generated by Django 3.2 on 2022-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_openingtime_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='weekday_close',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='weekday_open',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='weekend_close',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='weekend_open',
        ),
        migrations.AddField(
            model_name='opening',
            name='friday',
            field=models.CharField(default='timezone.now', max_length=12),
        ),
        migrations.AddField(
            model_name='opening',
            name='monday',
            field=models.CharField(default='timezone.now', max_length=12),
        ),
        migrations.AddField(
            model_name='opening',
            name='saturday',
            field=models.CharField(default='timezone.now', max_length=12),
        ),
        migrations.AddField(
            model_name='opening',
            name='sunday',
            field=models.CharField(default='timezone.now', max_length=12),
        ),
        migrations.AddField(
            model_name='opening',
            name='thursday',
            field=models.CharField(default='timezone.now', max_length=12),
        ),
        migrations.AddField(
            model_name='opening',
            name='tuesday',
            field=models.CharField(default='timezone.now', max_length=12),
        ),
        migrations.AddField(
            model_name='opening',
            name='wednesday',
            field=models.CharField(default='timezone.now', max_length=12),
        ),
    ]
