# Generated by Django 3.2 on 2022-02-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(max_length=125)),
                ('dish_description', models.CharField(max_length=250)),
                ('allergens', models.CharField(blank=True, max_length=120, null=True)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('dish_price', models.IntegerField()),
            ],
        ),
    ]
