# Generated by Django 3.2 on 2022-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=2)),
                ('number_of_Seats', models.IntegerField()),
                ('if_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('number_of_guests', models.IntegerField(max_length=1)),
                ('date_of_booking', models.DateField()),
                ('time_of_booking', models.TimeField()),
                ('special_requests', models.TextField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
