# Generated by Django 3.2 on 2022-02-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20220224_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=124)),
                ('full_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('number_of_guests', models.IntegerField()),
                ('date_of_booking', models.DateField()),
                ('time_of_booking', models.TimeField()),
                ('special_requests', models.TextField(blank=True, max_length=150, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_start', models.TimeField()),
                ('lunch_end', models.TimeField()),
                ('dinner_start', models.TimeField()),
                ('dinner_end', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='TableBooking',
        ),
        migrations.AddField(
            model_name='table',
            name='booking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.booking'),
        ),
    ]
