# Generated by Django 3.2 on 2022-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20220225_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number_of_Seats',
            new_name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='table',
            name='booking_info',
        ),
        migrations.AddField(
            model_name='table',
            name='booking_info',
            field=models.ManyToManyField(to='table.Booking'),
        ),
    ]
